### ISSUE TITLE
Version 1.9.0 seems to drop Send trait

### ISSUE THREAD

**Issue by hoytak** [artichoke/intaglio#239]
In upgrading to version 1.9.0, we hit a break with the following compilation error: 

```
325 | impl NFSFileSystem for MirrorFS {
    |                        ^^^^^^^^ `NonNull<OsStr>` cannot be sent between threads safely
    |
    = help: within `intaglio::internal::Interned<OsStr>`, the trait `Send` is not implemented for `NonNull<OsStr>`
```

This seems to be a regression from 1.8.*.  

This is with Cargo/rustc version 1.69.

**Comment by lopopolo** [comment]
Copying my comment from https://github.com/xetdata/xet-core/pull/80:

Thank you. This is a regression on my end. The symbol tables are no longer `Send`, `Sync`, and `Unpin` due to the way I fixed the soundness hole. I'm missing some trait impls on the new `PinBox` abstraction in the crate internals.

Later today I'll yank 1.9.0 and release 1.9.1 with the fixes.

Apologies for the breakage and thanks for the report!

**Comment by lopopolo** [comment]
@hoytak v1.9.1 is up which resolves the API breakage. Thanks again for the report!
